### PR TITLE
configuration tabs - mobile fix #133

### LINKED ISSUE #133: Configuration box on mobile isn't obvious
It's not really clear on mobile that there are multiple choice options. How can we improve this?image

### PR DESCRIPTION
**Pull request by GitGab19**
I changed the config option (that were used for the mobile view). 
I did it reusing the same structure used for medium/large devices (nav), with some little  adjustment for the size, to accomodate well all the 4 config.

Now it looks like this from my phone:

phone_screen

### CODE REVIEW

**Comment by GitGab19** [comment]
Test was failing because the majority of links in specifications.md were wrong.
Checked the updated README on https://github.com/stratum-mining/sv2-spec and FIXED all of them.
Pushed the updated version.
Now test should all pass.

**Comment by pavlenex** [comment]
Hey hey @GitGab19 thanks for your PR and welcome aboard 🚢 

This looks like a good approach to me, do you think we could justify align and  the supporters tabs below as well, would look a bit better?

IMG_7576

**Comment by GitGab19** [comment]
Thanks @pavlenex!
I fixed the text alignment and pushed the fixed version, it looks like this:

text-align-fix

**Review by pavlenex — APPROVED** [review]
Looks great! Thanks for the fix, congrats on your first SV2 contribution 🎉 

We do have a few more `good first issues` on the site ,feel free to check it out if you want :)

Also you can join our [Discord](https://discord.gg/fsEW23wFYs).

**Comment by GitGab19** [comment]
Yeah, I'll check them out! :)

I've already entered your Discord, since I'm working on my MD thesis, which is about Stratum V2 (and the entire evolution of the mining software since the first days of Bitcoin).
I'm currently studying Rust in order to start contributing on the development! 🔨

> Looks great! Thanks for the fix, congrats on your first SV2 contribution 🎉
> 
> We do have a few more `good first issues` on the site ,feel free to check it out if you want :)
> 
> Also you can join our [Discord](https://discord.gg/fsEW23wFYs).

**Pull request merged**
