### PR TITLE
Fixing social media preview image/description

### PR DESCRIPTION
**Pull request by joshr4**
In order to address issue https://github.com/stratum-mining/stratumprotocol.org/issues/147, the [open graph](https://ogp.me/) meta tags need to be updated.

I believe the reason the preview image isn't loading is due to the content url not being the full url to the asset.

### CODE REVIEW

**Comment by joshr4** [comment]
tested using opengraph.xyz - https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-150--startling-capybara-2231ea.netlify.app%2F

Screen Shot 2023-02-22 at 6 30 46 PM

The logo is a bit mis-sized, this may be fixed by using a dedicated logo of the right size.

**Comment by pavlenex** [comment]
@joshr4 Thanks for tackling this one, do you need an image in particular size/ratio, I can help with that, let's try to make it look right from the start :)

**Comment by joshr4** [comment]
@pavlenex looks like the image ought to be 1200x630 pixels, here is a nice article with more detailed information https://www.semantica.co.za/everything-you-need-to-know-about-open-graph-images-and-why-they-matter

**Comment by pavlenex** [comment]
Hey @joshr4 thanks for the resources. 

I am not a designer, but I tried to make something out of SV2 logo and background, it's not perfect but I think it will do the job. What do you think?


Twitter-cover-1200x400 v4

**Comment by joshr4** [comment]
@pavlenex looks great to me! I went ahead and added the new image. I also updated the content url I have in this PR, but since the new image isn't deployed to prod yet (https://stratumprotocol.org), it won't work. Once this PR is merged, and the image exists at that url, we should be good to go.

**Review by pavlenex — APPROVED** [review]

**Comment by pavlenex** [comment]
Thanks for your contribution @joshr4 🎉 

Feel free to pick up any other issues you find suitable in the repo.

If you know how to fix formatting in #145 please let me know :)

**Pull request merged**
