### PR TITLE
fix hero text

### LINKED ISSUE #63: Remove two dots `..` from the intro paragraph
Screenshot 2022-09-07 at 18 02 44

### PR DESCRIPTION
**Pull request by secondl1ght**
Fixes #63

### CODE REVIEW

**Review by pavlenex — CHANGES_REQUESTED** [review]
It kinds doubles the `improving decentralization` could we somehow just highlight `improve decentralization` in the paragraph already? Can just be a css, doesn't have to be herotext if it's not possible to higlight the text within a paragraph, what do you think?

**Comment by secondl1ght** [comment]
Oh sorry I didn't notice the copy got updated here - I have removed the double text and highlighted the text earlier in the paragraph.

**Comment by secondl1ght** [comment]
image

**Review by pavlenex — DISMISSED** [review]
Great update, lgtm!

**Comment by pavlenex** [comment]
@secondl1ght just as I hit the approve it seems conflict appeared, can you address it please?

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
