### PR TITLE
Create resource page #217 + #218

### PR DESCRIPTION
**Pull request by omerskywalker**
creation of resource page to display magazines, articles, videos, and various SV2-related content

### CODE REVIEW

**Comment by pavlenex** [comment]
Nice, preview works @omerskywalker but for build fails, any idea why?

**Comment by omerskywalker** [comment]
oh yep i see that, made some changes to local webpack to get live server running and accidentally pushed into the latest commit. have rolled that back and build should pass now. @pavlenex

**Comment by pavlenex** [comment]
@omerskywalker Seems to still fail.

**Comment by omerskywalker** [comment]
> @omerskywalker Seems to still fail.

realized the yarn.lock file needed to be re-built without package-lock.json interfering - should be to good to go now.

**Review by pavlenex — APPROVED** [review]
Awesome. Thanks for shipping this one 🚀 

CC @moneyball you may be happy to see we now have a resource page you suggested a while back

**Pull request merged**
