### PR TITLE
update tutorials

### PR DESCRIPTION
**Pull request by plebhash**
companion to https://github.com/stratum-mining/stratum/pull/726

### CODE REVIEW

**Comment by pavlenex** [comment]
I yet have to dig deep into reviewing the docs, but at the first glance it seems too detailed. Should we optimize for what we have in Google Docs already?

1. Run hosted setup
2. Run all roles

And just mention options for configuration, I was under impression we'll just port over entire Google Doc here and nuke anything else we have as currently this wall of text does seem a bit overwhelming.

**Comment by plebhash** [comment]
> I yet have to dig deep into reviewing the docs, but at the first glance it seems too detailed. Should we optimize for what we have in Google Docs already? As our goal for quick start is to allow anyone to test SV2 quickly.
> 
> 1. Run hosted setup
> 2. Run all roles
> 
> And just mention options for configuration, I was under impression we'll just port over entire Google Doc here and nuke anything else we have as currently this wall of text does seem a bit overwhelming.

indeed, I went through what we currently have (mostly focused on Config C and D).
but if the team agrees I can also just port over the Google Docs instructions over here.

@GitGab19 @Fi3 wdyt?

**Comment by plebhash** [comment]
or also @pavlenex can open a new PR going in this different direction, whatever you guys think is best

**Comment by GitGab19** [comment]
> > I yet have to dig deep into reviewing the docs, but at the first glance it seems too detailed. Should we optimize for what we have in Google Docs already? As our goal for quick start is to allow anyone to test SV2 quickly.
> > 
> > 1. Run hosted setup
> > 2. Run all roles
> > 
> > And just mention options for configuration, I was under impression we'll just port over entire Google Doc here and nuke anything else we have as currently this wall of text does seem a bit overwhelming.
> 
> indeed, I went through what we currently have (mostly focused on Config C and D) and updated it. but if the team agrees I can also just port over the Google Docs instructions over here.
> 
> @GitGab19 @Fi3 wdyt?

I agree with @pavlenex, now I would optimize what we have on the google doc as well.
It puts the focus on what we need to test more

**Pull request closed without merging**
