### PR TITLE
All the requested changes for issue.

### PR DESCRIPTION
**Pull request by 0xSaksham**
- [x]  Added Hut.io as an adopter.
- [x]  Removed entities mentioned in #194 
- [x] Moved "past-contributers" out of "all contributers"

image

### CODE REVIEW

**Comment by pavlenex** [comment]
Hey @0xSaksham thanks for your contribution. 🎉 

It seems good to me, seems you were able to figure out https://github.com/stratum-mining/stratumprotocol.org/issues/194#issuecomment-1987274585?

**Comment by 0xSaksham** [comment]
@pavlenex oh yes, that should be easy. I'll do it today.

**Comment by 0xSaksham** [comment]
- [x]  Hut8 added in "all contributors"

**Review by pavlenex — APPROVED** [review]
Awesome, thanks for your first contribution to the project 🎉

**Pull request merged**
