### PR TITLE
implementation and features rewrites

### PR DESCRIPTION
**Pull request by Kodylow**
Moved the copy I wrote previously into "Features", matching the https://braiins.com/stratum-v2 organization, and wrote summaries of the roles and sub-protocols for "Implementation.md"

### CODE REVIEW

**Comment by Kodylow** [comment]
addresses #28

**Comment by pavlenex** [comment]
Woah, thanks @Kodylow for tackling this, before we dig into reviewing it, could you confirm my understanding of the process.
So for now, you've used `overview` and `features` pages from https://braiins.com/stratum-v2 and re-wrote them from scratch?

**Comment by Kodylow** [comment]
I copied over everything from that page for content, features and overview, then rewrote it as I read through. Some examples

Ex.1: on the braiins site it has 4 roles with 1 sentence summaries, but per the spec there's actually 5 roles (template provider is separated out as a different role) so I detailed those differences.

Ex.2: the site refers to hashrate consumers instead of just pools, but we're referring to pools through the rest of the site so changed that role to pools and added a couple more lines explaining it. On the braiins site the copy is: 

Hashrate Consumer
An upstream node to which shares (i.e. completed jobs) are being submitted. The most common hashrate consumers are pools.


I changed this to:

Pools (Hashrate Consumers)
Pools operate as communication nodes to coordinate hashrate and distribute mining rewards. They create jobs for end-mining devices, validate blocks and shares, and propagate found blocks to the the Bitcoin Network. Pools do not custody or control hashrate. End-mining devices compatible with the Stratum protocol can switch between pools in minutes. Pools therefore compete for hashrate based on latency, ease-of-use, payout reliability, and associated networking services, all of which StratumV2 can significantly improve.

**Comment by Kodylow** [comment]
For the specs I think that's a @SeraBocca question on whether we can directly link those from a separate github repo but I think it should be possible. Rachel ported the entire spec into markdown files in the sv2-spec repo and vuepress looks like it autoformats markdown nicely, we could just adjust the spacing/headings to match Serabocca's design for the site. If we can't directly link it we could just copy the same markdown files over into this repo.

The parts that I rewrote so far here are separate from the spec though, they're from the braiins site (although there's a good amount of overlap with "03-Protocol-Overview" from the spec)

**Comment by pavlenex** [comment]
Yes, thanks for the detailed explanation, I just wanted to be sure.

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
